[package]
name = "events-aggregator"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async runtime
tokio = { workspace = true }
# NATS client
async-nats = "0.37"
# JSON serialization
serde = { workspace = true }
serde_json = { workspace = true }
# Logging and Observability
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"]}
# Error handling
anyhow = { workspace = true }
colored_json = "4"
futures = { workspace = true }
rand = { workspace = true }
