[workspace]
members = [
    "call-home",
    "console-logger",
    "metrics-exporter",
    "k8s/plugin",
    "k8s/supportability",
    "k8s/upgrade",
    "eventing-aggregator",
]

exclude = ["./dependencies/control-plane"]
resolver = "1"

[workspace.dependencies]
# k8s
k8s-openapi = { version = "0.24.0", default-features = false, features = ["v1_28", "schemars"] }
kube = { version = "0.99.0", default-features = false, features = ["runtime", "derive", "client", "rustls-tls", "aws-lc-rs"] }
schemars = { version = "0.8.21" }

# async
tokio = { version = "1.41.0", features = ["full"] }
tokio-retry = "0.3"
futures = "0.3"
async-trait = "0.1.83"
async-nats = { version = "0.47.0", default-features = false, features = ["aws-lc-rs", "jetstream"] }

# tracing
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }

# ser/deser
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"

# errors
snafu = "0.8.5"
anyhow = "1.0.92"

# misc
uuid = { version = "1.11.0", features = ["serde", "v4"] }
clap = { version = "4.5.20", features = ["cargo", "derive", "env", "string", "color"] }
nu-ansi-term = "0.50.1"
sha256 = "1.5.0"
chrono = "0.4.38"
rand = "0.8.5"
tempfile = "3.13.0"
humantime = "2.1.0"
once_cell = "1.20.2"
maplit = "1.0.2"
semver = { version = "1.0.23", features = ["serde"] }
regex = "1.11.1"
base64 = "0.22.1"
flate2 = "1.0.34"
tar = "0.4"
parse-size = "1.1.0"
downcast-rs = "1.2.1"
strum = "0.26.3"
strum_macros = "0.26.4"
time = "0.3"

# http
tonic = "0.13.1"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
reqwest-middleware = "0.5"
reqwest-retry = "0.9"
url = "2.5.4"
hyper = { version = "1.5.0", features = ["client", "http1", "http2"] }
hyper-util = "0.1.10"
tower = { version = "0.5.1", features = ["timeout", "util"] }
http = "1.1.0"
urlencoding = "2.1.3"
http-body-util = "0.1.2"

# exporter
actix-web = { version = "4.9.0", features = ["rustls-0_23"] }
prometheus = "0.13.4"
mime = "0.3.17"
prometheus-parse = "0.2.5"
heck = "0.5.0"
events-api = { path = "dependencies/control-plane/utils/dependencies/apis/events" }
prettytable-rs = "0.10.0"
