[package]
name = "upgrade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "upgrade-job"
path = "src/bin/upgrade-job/main.rs"

[lib]
name = "upgrade"
path = "src/lib.rs"

[dependencies]
openapi = { path = "../../dependencies/control-plane/openapi", default-features = false, features = ["tower-trace"] }
utils = { path = "../../dependencies/control-plane/utils/utils-lib" }
constants = { path = "../../constants" }
kube-proxy = { path = "../../dependencies/control-plane/k8s/proxy" }
console-logger = { path = "../../console-logger" }

kube = { workspace = true, features = ["derive", "runtime"] }
k8s-openapi = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "string", "color"] }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
humantime = { workspace = true }
maplit = { workspace = true }
serde = { workspace = true }
url = { workspace = true }
semver = { workspace = true, features = ["serde"] }
regex = { workspace = true }
snafu = { workspace = true }
tempfile = { workspace = true }
base64 = { workspace = true }
flate2 = { workspace = true }
tracing = { workspace = true }
