{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api-rest
  labels:
    app: api-rest
    {{ include "label_prefix" . }}/release: {{ .Release.Name }}
    {{ include "label_prefix" . }}/version: {{ .Chart.Version }}
spec:
  podSelector:
    matchLabels:
      app: api-rest
      {{ include "label_prefix" . }}/release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    # Allow inbound traffic
    - ports:
        # Allow HTTPS traffic
        - port: 8080
          protocol: TCP
    {{- if not .Values.security.tls.enabled }}
        # Allow HTTP traffic
        - port: 8081
          protocol: TCP
    {{- end }}
{{- end }}
