apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-io-engine
  labels:
    openebs.io/engine: io-engine
spec:
  selector:
    matchLabels:
      app: io-engine
  updateStrategy:
    type: OnDelete
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: io-engine
        openebs.io/logging: "true"
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      hostNetwork: true
      # To resolve services in the namespace
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector: {{- .Values.mayastor.nodeSelector | toYaml | nindent 8 }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
      {{- if .Values.base.metrics.enabled }}
      - name: metrics-exporter-pool
        image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}/mayastor-metrics-exporter-pool:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "-p{{ .Values.base.metrics.pollingInterval }}"
        command:
        - metrics-exporter-pool
        ports:
          - containerPort: 9502
            protocol: TCP
            name: metrics
      {{- end }}
      - name: io-engine
        image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}/mayastor-io-engine:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RUST_LOG
          value: {{ .Values.mayastor.logLevel }}
        - name: NVME_QPAIR_CONNECT_ASYNC
          value: "true"
        - name: NVMF_TCP_MAX_QUEUE_DEPTH
          value: "32"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        # The -l argument accepts cpu-list. Indexing starts at zero.
        # For example -l 1,2,10-20 means use core 1, 2, 10 to 20.
        # Note: Ensure that the CPU resources are updated accordingly.
        #       If you use 2 CPUs, the CPU: field should also read 2.
        - "-g$(MY_POD_IP)"
        - "-N$(MY_NODE_NAME)"
        - "-Rhttps://{{ .Release.Name }}-agent-core:50051"
        - "-y/var/local/io-engine/config.yaml"
        - "-l{{ include "cpuFlag" . }}"
        - "-p={{ .Release.Name }}-etcd:{{ .Values.etcd.service.port }}"
        - "--api-versions=v0"
        command:
        - io-engine
        securityContext:
          privileged: true
        volumeMounts:
        - name: device
          mountPath: /dev
        - name: udev
          mountPath: /run/udev
        - name: dshm
          mountPath: /dev/shm
        - name: configlocation
          mountPath: /var/local/io-engine/
        resources:
          limits:
            cpu: {{ .Values.mayastor.resources.limits.cpu | default .Values.mayastor.cpuCount | quote }}
            memory: {{ .Values.mayastor.resources.limits.memory | quote }}
            hugepages-2Mi: {{ .Values.mayastor.resources.limits.hugepages2Mi | quote }}
          requests:
            cpu: {{ .Values.mayastor.resources.requests.cpu | default .Values.mayastor.cpuCount | quote }}
            memory: {{ .Values.mayastor.resources.requests.memory | quote }}
            hugepages-2Mi: {{ .Values.mayastor.resources.requests.hugepages2Mi | quote }}
        ports:
        - containerPort: 10124
          protocol: TCP
          name: io-engine
      volumes:
      - name: device
        hostPath:
          path: /dev
          type: Directory
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: configlocation
        hostPath:
          path: /var/local/io-engine/
          type: DirectoryOrCreate
