[package]
name = "eventing-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
async-nats = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
parse-size = { workspace = true }
rand = { workspace = true }
clap = { workspace = true }
url = { workspace = true }
humantime = { workspace = true }
utils = { path = "../dependencies/control-plane/utils/utils-lib" }
event-consumer = { path = "../dependencies/control-plane/utils/event-consumer" }
events-api = { path = "../dependencies/control-plane/utils/dependencies/apis/events" }
shutdown = { path = "../dependencies/control-plane/utils/shutdown" }
