[package]
name = "supportability"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "supportability"
path = "src/lib.rs"

[features]
default = ["rls"]
openapi = []
rls = ["openapi/tower-client-rls"]
tls = ["openapi/tower-client-tls"]

[dependencies]
pstor = { path = "../../dependencies/control-plane/utils/pstor" }
platform = { path = "../../dependencies/control-plane/utils/dependencies/platform" }
openapi = { path = "../../dependencies/control-plane/openapi", default-features = false, features = ["tower-client", "tower-trace"] }
kube-proxy = { path = "../../dependencies/control-plane/k8s/proxy" }
kube-forward = { path = "../../dependencies/control-plane/k8s/forward" }
rest-plugin = { path = "../../dependencies/control-plane/control-plane/plugin", default-features = false }
utils = { path = "../../dependencies/control-plane/utils/utils-lib" }
hyper-body = { path = "../../dependencies/control-plane/utils/hyper-body" }
constants = { path = "../../constants" }

futures = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

kube = { workspace = true, features = ["derive"] }
k8s-openapi = { workspace = true }
schemars = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
humantime = { workspace = true }
uuid = { workspace = true }
once_cell = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
chrono = { workspace = true }
downcast-rs = { workspace = true }
parse-size = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true }

hyper = { workspace = true, features = ["client", "http1", "http2"] }
hyper-util = { workspace = true }
tower = { workspace = true, features = ["timeout", "util"] }
http = { workspace = true }
urlencoding = { workspace = true }
http-body-util = { workspace = true }
