apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator-diskpool
  labels:
    app: operator-diskpool
    helm-release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-diskpool
      helm-release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: operator-diskpool
        helm-release: {{ .Release.Name }}
        openebs.io/logging: "true"
    spec:
      serviceAccount: {{ .Release.Name }}-service-account
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: operator-diskpool
          resources:
            limits:
              cpu: {{ .Values.operators.pool.resources.limits.cpu | quote }}
              memory: {{ .Values.operators.pool.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.operators.pool.resources.requests.cpu | quote }}
              memory: {{ .Values.operators.pool.resources.requests.memory | quote }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}/{{ .Chart.Name }}-operator-diskpool:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-e http://{{ .Release.Name }}-api-rest:8081"
            - "-n{{ .Release.Namespace }}"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"
            - "--interval={{ .Values.base.cache_poll_period }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.operators.pool.logLevel }}
            {{- if default .Values.base.logSilenceLevel .Values.operators.pool.logSilenceLevel }}
            - name: RUST_LOG_SILENCE
              value: {{ default .Values.base.logSilenceLevel .Values.operators.pool.logSilenceLevel }}
            {{- end }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
