---
{{ if and .Values.loki-stack.persistence.enabled (eq .Values.loki-stack.persistence.storageClassName "manual") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-volume-0
  labels:
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-loki-0
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: {{ index .Values "loki-stack" "loki" "persistence" "reclaimPolicy" }}
  capacity:
    storage: {{ index .Values "loki-stack" "loki" "persistence" "size" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/{{ .Release.Name }}/loki"
---
{{- end }}
