apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-core
  labels:
    app: agent-core
    helm-release: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: agent-core
  ports:
    - name: grpc
      port: 50051
    - name: ha-cluster
      port: 50052
