[package]
name = "kubectl-plugin"
description = "Kubectl Plugin"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "kubectl-mayastor"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rls"]
openapi = []
rls = ["openapi/tower-client-rls", "rest-plugin/rls"]
tls = ["openapi/tower-client-tls", "rest-plugin/tls"]


[dependencies]
openapi = { path = "../../dependencies/control-plane/openapi", default-features = false, features = ["tower-trace"] }
utils = { path = "../../dependencies/control-plane/utils/utils-lib" }
constants = { path = "../../constants" }
rest-plugin = { path = "../../dependencies/control-plane/control-plane/plugin", default-features = false }
supportability = { path = "../supportability" }
upgrade = { path = "../upgrade" }
events-api = { workspace = true }
prettytable-rs = { workspace = true }
strum = { workspace = true }
shutdown = { path = "../../dependencies/control-plane/utils/shutdown" }

kube = { workspace = true, features = ["derive", "runtime", "ws"] }
k8s-openapi = { workspace = true }
kube-proxy = { path = "../../dependencies/control-plane/k8s/proxy" }
kube-forward = { path = "../../dependencies/control-plane/k8s/forward" }
tokio = { workspace = true, features = ["time"] }
anyhow = { workspace = true }
clap = { workspace = true }
async-trait = { workspace = true }
humantime = { workspace = true }
http = { workspace = true }
snafu = { workspace = true }

# The DiskPool resource is used in this crate via the include! macro.
# These dependencies are required to build that file.
chrono = { workspace = true }
parse-size = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
schemars = { workspace = true }
