name: Develop to Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  prepareReleaseBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./scripts/helm/shell.nix
      - name: Check if the chart is publishable
        run: |
          branch="${{ github.ref_name }}"
          nix-shell --pure --run "./scripts/helm/publish-chart-yaml.sh --check-chart "$branch" --develop-to-release" ./scripts/helm/shell.nix
      - name: Check if the submodules are correct
        run: |
          branch="${{ github.ref_name }}"
          ./scripts/git/set-submodule-branches.sh --branch "$branch"
      - name: Update the Chart Readme.md
        run: nix-shell ./scripts/helm/shell.nix --pure --run "SKIP_GIT=1 ./scripts/helm/generate-readme.sh"
      - name: Update the Chart images
        run: |
          nix-shell ./scripts/helm/shell.nix --pure --run "./scripts/helm/images.sh generate --dependency-update"
          nix-shell ./scripts/helm/shell.nix --pure --run "./scripts/helm/images.sh patch"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(ci): update helm chart versions and/or git submodules"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Prepare release branch
          labels: |
            area/helm
            kind/ci
          draft: false
          signoff: true
          delete-branch: true
          branch: "prepare-${{ github.ref_name }}"
          token: ${{ secrets.ORG_CI_GITHUB }}
      - name: Approve Pull Request by CI Bot
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Approve Pull Request by CI User 2
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB_2 }}
      - name: Queue Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr comment ${{ steps.cpr.outputs.pull-request-number }} --body "@mergify queue"
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB }}
