name: Develop Helm Chart
on:
  push:
    branches:
      - develop
    paths:
      - 'chart/**'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./scripts/helm/shell.nix

      - name: Publish locally in the workspace
        run: |
          branch="${{ github.ref_name }}"
          nix-shell --pure --run "./scripts/helm/publish-chart-yaml.sh --check-chart "$branch"" ./scripts/helm/shell.nix
          nix-shell --pure --run "SKIP_GIT=1 ./scripts/helm/generate-readme.sh" ./scripts/helm/shell.nix

      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        env:
          TMPDIR: /tmp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
