name: Helm Testing Chart
on:
  push:
    branches:
      - 'helm-testing/**'
      - '!helm-testing/**-staging**'
    paths:
      - 'chart/**'
      - '.github/**'

jobs:
  helm-testing-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./scripts/helm/shell.nix
      - name: Update chart
        run: |
          # Update logLevel to 'debug'
          sed -Ei "s~(logLevel: .*)~logLevel: debug~" chart/values.yaml
          # Update repo url/name across all chart files
          sed -i "s/mayastor-extensions/mayastor-chart-donotuse/g" chart/*.*
      - name: Check if the chart is publishable
        run: |
          branch="${{ github.ref_name }}"
          nix-shell --pure --run "./scripts/helm/publish-chart-yaml.sh --check-chart "$branch"" ./scripts/helm/shell.nix
      - name: Publish Mayastor Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        env:
          TMPDIR: /tmp
        with:
          token: ${{ secrets.CI_BOT_1_RAISE_PRS }}
          charts_dir: .
          repository: mayastor-chart-donotuse
          branch: gh-pages
