name: Submodule Update
on:
  workflow_dispatch:
  workflow_call:

jobs:
  submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ./.github/actions/setup-nix
      - name: Update submodules
        run: |
          ./scripts/git/set-submodule-branches.sh -u

      - id: set-target
        run: |
          version=$(nix-shell -p yq-go --run "yq '.appVersion' chart/Chart.yaml")
          echo "branch=${version}_mod_update" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(ci): update git submodules"
          committer: GitHub <noreply@github.com>
          title: "[CI] Update git submodules"
          draft: false
          signoff: true
          delete-branch: true
          branch: ${{ steps.set-target.outputs.branch }}
          token: ${{ secrets.ORG_CI_GITHUB }}
      - name: Approve Pull Request by CI Bot
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Approve Pull Request by CI User 2
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB_2 }}
      - name: Queue Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr comment ${{ steps.cpr.outputs.pull-request-number }} --body "@mergify queue"
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB }}
