name: CI
on:
  workflow_call:
  push:
    branches:
      - staging
      - trying
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

jobs:
  lint-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/lint.yml
  helm-ci:
    uses: ./.github/workflows/helm-chart.yml
    secrets: inherit
    with:
      trigger: ${{ github.event_name }}
  int-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/unit-int.yml
  image-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/image-pr.yml
  k8s-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/k8s-ci.yml
    secrets: inherit
  bors-ci:
    if: ${{ !cancelled() && github.event_name != 'pull_request' }}
    needs:
      - lint-ci
      - helm-ci
      - int-ci
      - image-ci
      - k8s-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
