name: Update future chart version on tag push
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  update-chart:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./scripts/helm/shell.nix
      - name: Publish locally in the workspace
        run: |
          tag="${{ github.ref_name }}"
          BASE_REF="${{ github.event.base_ref }}"
          if [ -n "$BASE_REF" ]; then
            BRANCH="${BASE_REF#refs/heads/}"
          else
            BRANCH="$(nix-shell --pure --run "./scripts/helm/find-released-branch.sh "$tag"" ./scripts/helm/shell.nix)"
          fi
          echo "BASE_BRANCH=$BRANCH" >> $GITHUB_ENV

          nix-shell --pure --run "./scripts/helm/publish-chart-yaml.sh --released "$tag" --released-branch "$BRANCH"" ./scripts/helm/shell.nix
          nix-shell --pure --run "SKIP_GIT=1 ./scripts/helm/generate-readme.sh" ./scripts/helm/shell.nix
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(ci): update future helm chart versions"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Bump future helm chart version on the release branch
          labels: |
            area/helm
            kind/ci
          draft: false
          signoff: true
          delete-branch: true
          base: ${{ env.BASE_BRANCH }}
          branch: "update-chart-${{ env.BASE_BRANCH }}"
          token: ${{ secrets.ORG_CI_GITHUB }}
      - name: Approve Pull Request by CI Bot
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Approve Pull Request by CI User 2
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr review ${{ steps.cpr.outputs.pull-request-number }} --approve
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB_2 }}
      - name: Queue Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          gh pr comment ${{ steps.cpr.outputs.pull-request-number }} --body "@mergify queue"
        env:
          GH_TOKEN: ${{ secrets.ORG_CI_GITHUB }}
