[package]
name = "call-home"
version = "0.1.0"
edition = "2021"
description = "Call-home for observability"


[lib]
name = "obs"
path = "src/lib.rs"

[[bin]]
name = "obs-callhome"
path = "src/bin/callhome/main.rs"

[[bin]]
name = "obs-callhome-stats"
path = "src/bin/stats/main.rs"

[dependencies]
constants = { path = "../constants" }
openapi = { path = "../dependencies/control-plane/openapi" }
utils = { path = "../dependencies/control-plane/utils/utils-lib" }
events-api = { path = "../dependencies/control-plane/utils/dependencies/apis/events" }


kube = { workspace = true, features = ["runtime", "derive"] }
k8s-openapi = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha256 = { workspace = true }
url = { workspace = true }
snafu = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
humantime = { workspace = true }
once_cell = { workspace = true }

tokio-retry = { workspace = true }

# exporter
actix-web = { workspace = true }
prometheus = { workspace = true }
mime = { workspace = true }

# parse prometheus output
prometheus-parse = { workspace = true }
heck = { workspace = true }
